### ISSUE TITLE
You should make this a private repo or delete this. 

### ISSUE THREAD

**Issue by javawolfpack** [jdstone/csci311#1]

**Comment by jdstone** [comment]
Why?

**Comment by javawolfpack** [comment]
It's a violation of the honesty policy of the CSCI311 syllabus. Sharing code from coursework is frowned upon professionally and academically. Additionally, some schools will revoke your degree for academic dishonesty, so it's better not to risk having your code stolen by a current student and having to worry about this.

**Comment by jdstone** [comment]
Can you help me understand why it's okay to share code (open source), but not share code from coursework?  How is it any different?

**Comment by javawolfpack** [comment]
Open source code is code you developed for either yourself or for work. If it was developed for work if you didn't get express permission to make it open-source you are likely to get sued/fired if they are not okay with it. Similarly code for coursework is not able to be shared in the open source community as there are restrictions on this code, unless otherwise stated in the course/syllabus. And as the courses you have on github CSCI311/340 explicitly state you cannot share code from the class in the syllabus this is a violation of the honesty policies of these courses.

**Comment by jdstone** [comment]
Cool!  Thanks for the clarification!
